name: fallstudie
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/trophy_titles.json
